// Generated by Payload (`pnpm --filter @titanica/web generate:importmap`).
// Empty until custom admin components are registered. Kept in the repo so the admin
// route group compiles on a fresh checkout before the first generate step runs.
export const importMap = {}
